---
title: "STAT3799 SVM"
author: "YANG Yunqian"
date: "4 October 2020"
output:
  pdf_document: default
  html_document: default
---

#Data Processing
```{r}
setwd('/Users/yangyunqian/Desktop/STAT3799/HKdata')
data_dir='/Users/yangyunqian/Desktop/STAT3799/HKdata'
library(TTR)
library(quantmod)
library(rvest)
library(xts)
library(Hmisc)
filePaths <- list.files(data_dir, "\\.csv$", full.names = TRUE)
N<-length(filePaths)
code.name<-array(1:N)
data.list<-list()
for (i in 1:N){
  name<-strsplit(filePaths[i], '/')[[1]][7]
  name<-strsplit(name,split=".",fixed=TRUE)[[1]][1]
  code.name[i]=name
  data<-read.csv(filePaths[i],i)
  data.list[[name]]=data
  rm(data)
  rm(name)
}
#max
lag.max<-function(arr,windows=9){
 N<-length(arr)
 result<-matrix(NA, N, 1) 
 for (i in 1:N){
   if (i<9){
     result[i]=max(arr[1:i])
   }
   else{
     result[i]=max(arr[i-8:i])
   }
 }
 return(result)
}
#min
lag.min<-function(arr,windows=9){
  N<-length(arr)
  result<-matrix(NA, N, 1) 
  for (i in 1:N){
    if (i<9){
      result[i]=min(arr[1:i])
    }
    else{
      result[i]=min(arr[i-8:i])
    }
  }
  return(result)
}

KDJ<-function(data,windows=9){
  l_temp <- nrow(data)        
  KDJ <- matrix(50, l_temp, 3)    
  KDJ <- as.data.frame(KDJ)       
  colnames(KDJ) <- c('K', 'D', 'J')
  KDJ[1:(windows-1), ]  <- 50               
 
  high_max <- lag.max(data$High)
 
  low_min <-  lag.min(data$Low)
  # rsv
  rsv <- (data$Close - low_min) / (high_max - low_min) * 100
 
  for (i in windows:l_temp) {
  
    KDJ[i, 1] <- 2/3 * KDJ[(i - 1), 1] + 1/3 * rsv[i, ]
    
    KDJ[i, 2] <- 2/3 * KDJ[(i - 1), 2] + 1/3 * KDJ[i, 1]
    KDJ[i, 3] <- 3 * KDJ[i, 1] - 2 * KDJ[i, 2]
  }
  
  return (KDJ)
}
Williams<-function(data,windows=14){
  high_max <- lag.max(data$High,windows)
  
  low_min <-  lag.min(data$Low,windows)
  result<-100-(data$Close-low_min)/(high_max-low_min)*100
  return(result)
}

label<-function(arr){
  N<-length(arr)
  K<-kmeans(arr,5) #k-means clustering
  K<-sort(K$centers)
  result<-matrix(NA, N, 1) 
  for (i in 1:N){
    if (arr[i]>K[5]){
      result[i]=1
    }
     else if(arr[i]>K[4]){
      result[i]=2
    }
     else if(arr[i]>K[3]){
      result[i]=3
    }
    else if (arr[i]>K[2]){
      result[i]=4
    }
    else{
      result[i]=5
    }
  }
  return(result)
}

```

#Build models and forecasts
```{r}
library(e1071)
test.data.list<-list()
train.data.list<-list()
for (i in 1:N){
  name<-code.name[i]
  data<-data.list[[name]]
  data$MACD<-MACD(data$Close)[,1]
  data$RSI<-RSI(data$Close)
  data$KDJ<-KDJ(data,7)[,3] # parameter = 7 #use J value only
  impute <- function(x, x.impute){ifelse(is.na(x),x.impute,x)}
           
  data$KDJ<-impute(data$KDJ, 50)        #specific values
  data$KDJ<-impute(as.vector(data$KDJ), 50)  
  data$Williams<-Williams(data,10) # parameter = 10
  data$return<-c(0,data$Close[2:length(data$Close)]/data$Close[1:(length(data$Close)-1)]-1)
  data$label<-label(data$return)
  #data$label<-kmeans(data$return,5)$
  data<-na.omit(data)
  train.data<-data
  test.data<-data
  train.data<-train.data[train.data$Date<'2017-01-01',] #set dates before year 2017 as training data
  test.data<-test.data[test.data$Date>='2017-01-01',] #set dates after 1 January, 2017 as testing data
  train.data.list[[name]]<-train.data
  test.data.list[[name]]<-test.data
  model<-svm(label~.,data=train.data.list[[name]][,c(8,9,10,11,13)]) #svm
  pred<-round(predict(model,test.data.list[[name]][,c(8,9,10,11)])) #prediction
  test.data$pred<-pred
  test.data.list[[name]]<-test.data
}
```
#Draw candlestick chart, MACD and RSI chart
```{r}
library(tidyverse)
library(gridExtra)
library(quantmod)  #need to use SVA function
k_plot<-function(code){
df<-data.list[[code]]
myvars <- c("Open","High","Low","Close","Volume")
data <- xts(df[myvars], order.by=as.Date(as.character(df[,1]),format="%Y-%m-%d"))
head(data)
stock <-data
chartSeries(x=stock["2013-01-01/"], name=code.name[code], line.type="l", bar.type="ohcl", 
        theme="white", up.col='red', dn.col='green',
	TA="addMACD();addRSI();")
}
k_plot(1)
k_plot(2)
k_plot(3)
k_plot(4)
```
#Graph of KDJ indicator
```{r}
library(ggplot2)
plot_KDJ<-function(code){
  data<-data.list[[code]]
  data$Date<-as.Date(data$Date, '%Y-%m-%d', tz='GMT')
  data$KDJ<-KDJ(data)[,3]
  ggplot(data,aes(x = Date, y = KDJ, group = 1)) + geom_line(linetype="dotted") + geom_point(size=0.05, shape=0.01) +
    xlab("Date") + ylab("KDJ") +
    ggtitle(code.name[code])
}
plot_KDJ(0001)
plot_KDJ(0002)
plot_KDJ(0003)
plot_KDJ(0004)
```
#Graph of KDJ indicator
```{r}
library(ggplot2)
plot_Williams<-function(code){
  data<-data.list[[code]]
  data$Date<-as.Date(data$Date, '%Y-%m-%d', tz='GMT')
  data$Williams<-Williams(data)
  ggplot(data,aes(x = Date, y =Williams, group = 1)) + geom_line(linetype="dotted") + geom_point(size=0.05, shape=0.01) +
    xlab("Date") + ylab("Williams") +
    ggtitle(code.name[code])
}
plot_Williams(0001)
plot_Williams(0002)
plot_Williams(0003)
plot_Williams(0004)
```
#Backtesting
```{r}
data_money=list()
for (j in 1:50){
  code=code.name[j]
  data=test.data.list[[j]]
   N<-length(data$Date)
 
  balance.money<-matrix(0, N, 1) 
  code.money<-matrix(0, N, 1) 
  money<-matrix(0, N, 1)
  for (i in 1:N){
  if (i==1){
    balance.money[i]=200000
  }
    else{
       balance.money[i]=balance.money[i-1]
       code.money[i]=code.money[i-1]
    }
  if ((data$pred[i]==1|data$pred[i]==2)&code.money[i]==0){
      if (balance.money[i]-floor(balance.money[i]/data$Close[i])*data$Close[i]-floor(balance.money[i]/data$Close[i])*data$Close[i]*0.00036<0){
        b=balance.money[i]-(floor(balance.money[i]/data$Close[i])-1)*data$Close[i]-(floor(balance.money[i]/data$Close[i])-1)*data$Close[i]*0.00036
         code.money[i]=(floor(balance.money[i]/data$Close[i])-1)*data$Close[i]
         balance.money[i]=b
      }
      else{
    b=balance.money[i]-floor(balance.money[i]/data$Close[i])*data$Close[i]-floor(balance.money[i]/data$Close[i])*data$Close[i]*0.00036
    code.money[i]=floor(balance.money[i]/data$Close[i])*data$Close[i] 
   balance.money[i]=b }
 
    }
   
     
    else{
      if (code.money[i]>0){
      code.money[i]= code.money[i]*(1+data$return[i])
      
      
      }
    if (code.money[i]>0 &(data$pred[i]==4|data$pred[i]==5)){
      balance.money[i]=balance.money[i]+code.money[i]
      code.money[i]=0
      
    }   
    }
    money[i]=code.money[i]+balance.money[i]
  }
  
  money<-data.frame(money)
  money$date<-data$Date
  data_money[[code]]=money
}
 money<-matrix(0, N, 1)
  
for (i in 1:N){
  for (j in 1:50){
  code=code.name[j]
  data=data_money[[j]]
  money[i]=data$money[i]+money[i]
  }
}
 money<-data.frame(money)
  money$date<-data$date
  print(money)
```
#Evaluation of backtesting results
```{r}
dates <- as.Date(money$date, "%Y-%m-%d")
plot(dates,money$money/(200000*50), type="l", lwd=1, main="Net Worth Chart", xlab="Date",ylab="Net Value",ylim=c(0.5,4.0), col="Blue")
library(tseries)
library(PerformanceAnalytics)
#maximum drawdown rate
mdd <- maxdrawdown(money$money[1:(N-1)]/(200000*50))
print(mdd)

ggplot(money,aes(x = as.Date(date), y =money, group = 1)) + geom_line(linetype="dotted", color="red") + geom_point(size=0.05, shape=0.01, color="red") +xlab("Date") + ylab("Money") + scale_x_date(date_breaks = "1 month", date_labels = "%B") + theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5)) + ggtitle("Cumulative net worth chart") 

library(PerformanceAnalytics)
N=length(money$money)
money$return=c(0,money$money[2:N]/money$money[1:(N-1)]-1)
rownames(money)=as.Date(money$date, '%Y-%m-%d', tz='GMT')
return<-data.frame(money$return)
rownames(return)=as.Date(money$date, '%Y-%m-%d', tz='GMT')
return<-na.omit(return)

#annual average rate of return
Return.annualized(return)
#annual standardized deviation
StdDev.annualized(return)
#annual sharpe ratio
ann_sharpe <- (Return.annualized(return) / StdDev.annualized(return))

# Sharp ratio is calculated by subtracting the average excess return from the risk-free interest rate and dividing by the volatility
# Use the function table.AnnualizedReturns() to get all the above results at once
ann_sharpe
plot(return$money.return,type='l',xlab="time",col="DeepPink", main="Rate of return")
```